import json

f = open("mapa-virtual.json")
bd = json.load(f)
f.close()

print("""@prefix : <http://rpcw.di.uminho.pt/2024/2/untitled-ontology-18/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@base <http://rpcw.di.uminho.pt/2024/2/untitled-ontology-18/> .

<http://rpcw.di.uminho.pt/2024/2/untitled-ontology-18> rdf:type owl:Ontology .

#################################################################
#    Object Properties
#################################################################

###  http://rpcw.di.uminho.pt/2024/2/untitled-ontology-18#destino
:destino rdf:type owl:ObjectProperty ;
         rdfs:domain :ligacao ;
         rdfs:range :cidade .


###  http://rpcw.di.uminho.pt/2024/2/untitled-ontology-18#origem
:origem rdf:type owl:ObjectProperty ;
        rdfs:domain :ligacao ;
        rdfs:range :cidade .


#################################################################
#    Data properties
#################################################################

###  http://rpcw.di.uminho.pt/2024/2/untitled-ontology-18#cidadeDescricao
:cidadeDescricao rdf:type owl:DatatypeProperty ;
                 rdfs:domain :cidade ;
                 rdfs:range xsd:string .


###  http://rpcw.di.uminho.pt/2024/2/untitled-ontology-18#cidadeDistrito
:cidadeDistrito rdf:type owl:DatatypeProperty ;
                rdfs:domain :cidade ;
                rdfs:range xsd:string .


###  http://rpcw.di.uminho.pt/2024/2/untitled-ontology-18#cidadeId
:cidadeId rdf:type owl:DatatypeProperty ;
          rdfs:domain :cidade ;
          rdfs:range xsd:string .


###  http://rpcw.di.uminho.pt/2024/2/untitled-ontology-18#cidadeNome
:cidadeNome rdf:type owl:DatatypeProperty ;
            rdfs:domain :cidade ;
            rdfs:range xsd:string .


###  http://rpcw.di.uminho.pt/2024/2/untitled-ontology-18#cidadePopulacao
:cidadePopulacao rdf:type owl:DatatypeProperty ;
                 rdfs:domain :cidade ;
                 rdfs:range xsd:string .


###  http://rpcw.di.uminho.pt/2024/2/untitled-ontology-18#ligacaoDestino
:ligacaoDestino rdf:type owl:DatatypeProperty ;
                rdfs:domain :ligacao ;
                rdfs:range xsd:string .


###  http://rpcw.di.uminho.pt/2024/2/untitled-ontology-18#ligacaoDistancia
:ligacaoDistancia rdf:type owl:DatatypeProperty ;
                  rdfs:domain :ligacao ;
                  rdfs:range xsd:float .


###  http://rpcw.di.uminho.pt/2024/2/untitled-ontology-18#ligacaoId
:ligacaoId rdf:type owl:DatatypeProperty ;
           rdfs:domain :ligacao ;
           rdfs:range xsd:string .


###  http://rpcw.di.uminho.pt/2024/2/untitled-ontology-18#ligacaoOrigem
:ligacaoOrigem rdf:type owl:DatatypeProperty ;
               rdfs:domain :ligacao ;
               rdfs:range xsd:string .


#################################################################
#    Classes
#################################################################

###  http://rpcw.di.uminho.pt/2024/2/untitled-ontology-18#cidade
:cidade rdf:type owl:Class .


###  http://rpcw.di.uminho.pt/2024/2/untitled-ontology-18#ligacao
:ligacao rdf:type owl:Class .


#################################################################
#    Individuals
#################################################################
""")

for cidade in bd['cidades']:
        print(f"""
###  http://rpcw.di.uminho.pt/2024/2/untitled-ontology-18#{cidade['id']}
:{cidade['id']} rdf:type owl:NamedIndividual ,
              :cidade ;
     :cidadeDescricao "{cidade['descrição']}" ;
     :cidadeDistrito "{cidade['distrito']}" ;
     :cidadeId "{cidade['id']}" ;
     :cidadeNome "{cidade['nome']}" ;
     :cidadePopulacao "{cidade['população']}" .
""")
        
for ligacao in bd['ligacoes']:
        print(f"""

###  http://rpcw.di.uminho.pt/2024/2/untitled-ontology-18#{ligacao['id']}
:{ligacao['id']} rdf:type owl:NamedIndividual ,
               :ligacao ;
      :destino :{ligacao['destino']} ;
      :origem :{ligacao['origem']} ;
      :ligacaoDistancia "{ligacao['distância']}"^^xsd:float ;
      :ligacaoId "{ligacao['id']}" .
""")
        
print("###  Generated by the OWL API (version 4.5.26.2023-07-17T20:34:13Z) https://github.com/owlcs/owlapi")
